version: "3.9"
services: 
  db:
    restart: always
    image: postgres
    container_name: postgres
    env_file:
      - .env 
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - '5433:5432'
    networks: 
      - backend

  rabbitmq: 
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    tty: true
    networks: 
      - backend
    ports: 
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ./rabbit-data:/var/lib/rabbitmq

  user:
    build: 
      context: ./user
      dockerfile: Dockerfile
    image: cablegram/user
    container_name: cablegram_user_microservice
    restart: always
    env_file: 
      - .env
    depends_on: 
      - db
      - rabbitmq
    networks: 
      - backend

  room: 
    build:
      context: ./room
      dockerfile: Dockerfile
    image: cablegram/room
    container_name: cablegram_room_microservice
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    networks: 
      - backend
    
  auth:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    image: cablegram/auth
    container_name: cablegram_auth_microservice
    restart: always
    env_file: 
      - .env
    depends_on:
      - rabbitmq
    networks:
      - backend

  notification:
    build:
      context: ./notification
      dockerfile: Dockerfile
    image: cablegram/notification
    container_name: cablegram_notification_microservice
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - backend
    ports:
      - "3000:3000"

  message: 
    build: 
      context: ./message
      dockerfile: Dockerfile
    image: cablegram/message
    container_name: cablegram_message_microservice
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend

  gateway: 
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    image: cablegram/gateway
    container_name: cablegram_gateway
    depends_on: 
      - rabbitmq
      - user
      - message
      - notification
      - auth
      - room
    restart: always
    env_file: 
      - .env
    networks: 
      - backend
    ports: 
      - '8000:3000'
    
networks: 
  backend: 
    driver: bridge